#!/usr/bin/env python2

import sys
import os
import platform
from saltlocal import getSaltCall





if __name__ == "__main__":
    prefix = os.path.abspath(os.path.join(os.path.dirname(sys.argv[0]), ".."))
    caller = getSaltCall(prefix)
    caller.run(sys.argv[1:])
